backend = "glx";
vsync = true;

corner-radius = 12;
#round-borders = 1;
#round-borders-rule = [
#"12:class_g = 'firefox'"
#];
#border-width = 2
#border-color = "#fd754e";

rounded-corners-exclude = [
"_GTK_FRAME_EXTENTS@:c",
"windows_type = 'dock'",
"windows_type = 'desktop'"
];

shadow = false;
shadow-radius = 12;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.4;

shadow-exclude = [
"windows_type = 'dock'",
"windows_type = 'desktop'"
];

inactive-opacity = 1;
active-opacity = 1;

blur:
{
method = "dual_kawase";
strength = 3;
};

mark-wmwin-focused = true;
mark-ovredir-focused = true;

fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 10;
